(() => {
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  let db, user, currentSessionId, liveChannel, sessionChannel, activeReviewId = null;
  let sessions = [], knowledge = [], triage = [], reviews = [];

  const setStatus=(el,text,type='')=>{el.textContent=text;el.className=`status ${type}`.trim()};
  const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=d=>{try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(d))}catch{return ''}};

  async function init(){
    const config=await fetch('/api/config').then(r=>r.json());
    if(!config.configured){setStatus($('#loginStatus'),'Configure o Supabase na Vercel antes de acessar o painel.','error');return;}
    db=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey);
    const {data:{session}}=await db.auth.getSession();
    if(session) await enterApp(session.user);
  }
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();setStatus($('#loginStatus'),'Entrando...');const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)return setStatus($('#loginStatus'),error.message,'error');await enterApp(data.user);});
  $('#logoutBtn').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});

  async function enterApp(u){
    const {data:profile}=await db.from('admin_profiles').select('*').eq('user_id',u.id).eq('active',true).maybeSingle();
    if(!profile){await db.auth.signOut();return setStatus($('#loginStatus'),'Este usuário não está autorizado no painel. Execute novamente o SQL de configuração após criar o usuário.','error');}
    user=u;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');
    await Promise.all([loadSettings(),loadSessions(),loadKnowledge(),loadTriage(),loadReviews()]);subscribeLive();setInterval(()=>loadSessions().catch?.(()=>{}),15000);
  }

  $$('#appView nav button').forEach(btn=>btn.addEventListener('click',()=>showTab(btn.dataset.tab)));
  function showTab(name){$$('#appView nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab').forEach(t=>t.classList.toggle('active',t.id===`tab-${name}`));const titles={live:['Atendimentos ao vivo','Acompanhe as conversas e assuma quando necessário.'],knowledge:['Base de respostas','Edite e publique respostas sem fazer novo upload.'],triage:['Triagem','Organize as perguntas que seguem para o WhatsApp.'],review:['Sugestões','Revise respostas humanas antes de incorporá-las.'],settings:['Configurações','Ajustes gerais do atendimento.']};$('#pageTitle').textContent=titles[name][0];$('#pageSubtitle').textContent=titles[name][1];}

  async function loadSettings(){const {data}=await db.from('chat_settings').select('*');const map=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));$('#availabilityToggle').checked=map.human_available===true;$('#availabilityText').textContent=map.human_available?'Visitantes podem solicitar atendimento aqui.':'A IA e o WhatsApp continuam disponíveis.';$('#settingWhatsapp').value=map.whatsapp_number||'5511981210932';$('#settingWelcome').value=map.welcome_message||'';$('#settingRetention').value=map.retention_days||90;}
  $('#availabilityToggle').addEventListener('change',async e=>{await upsertSetting('human_available',e.target.checked);$('#availabilityText').textContent=e.target.checked?'Visitantes podem solicitar atendimento aqui.':'A IA e o WhatsApp continuam disponíveis.';});
  async function upsertSetting(key,value){return db.from('chat_settings').upsert({key,value,updated_by:user.id,updated_at:new Date().toISOString()});}
  $('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();setStatus($('#settingsStatus'),'Salvando...');const results=await Promise.all([upsertSetting('whatsapp_number',$('#settingWhatsapp').value.replace(/\D/g,'')),upsertSetting('welcome_message',$('#settingWelcome').value.trim()),upsertSetting('retention_days',Number($('#settingRetention').value||90))]);const err=results.find(x=>x.error)?.error;setStatus($('#settingsStatus'),err?err.message:'Configurações salvas.',err?'error':'success');});

  async function loadSessions(){let q=db.from('chat_sessions').select('*').order('last_activity',{ascending:false}).limit(100);const filter=$('#sessionFilter').value;if(filter==='open')q=q.neq('status','closed');else if(filter!=='all')q=q.eq('status',filter);const {data,error}=await q;if(!error){const base=data||[];const ids=base.map(x=>x.id);let triageMap={};if(ids.length){const {data:subs}=await db.from('triage_submissions').select('session_id,reference_code,summary_text').in('session_id',ids);triageMap=Object.fromEntries((subs||[]).map(x=>[x.session_id,x]));}sessions=base.map(x=>({...x,triage_submissions:triageMap[x.id]||null}));renderSessions();}}
  $('#sessionFilter').addEventListener('change',loadSessions);
  function renderSessions(){const box=$('#sessionList');box.innerHTML=sessions.map(s=>`<div class="session-item ${s.id===currentSessionId?'active':''}" data-id="${s.id}"><span class="pill ${s.status}">${({bot:'IA',waiting_human:'aguardando',human:'humano',closed:'encerrado'})[s.status]}</span><strong>${escapeHtml(s.visitor_name||'Visitante')}</strong><small>${fmt(s.last_activity)} · ${s.id.slice(0,8)}${s.triage_submissions?.reference_code?' · '+escapeHtml(s.triage_submissions.reference_code):''}</small></div>`).join('')||'<div class="empty">Nenhuma conversa.</div>';box.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>openSession(el.dataset.id)));const waiting=sessions.filter(s=>s.status==='waiting_human').length;$('#liveBadge').textContent=waiting||'';document.title=waiting?`(${waiting}) Painel do Chatbox | Resumindo Viagens`:'Painel do Chatbox | Resumindo Viagens';}
  async function openSession(id){currentSessionId=id;renderSessions();$('#emptyConversation').classList.add('hidden');$('#conversationView').classList.remove('hidden');const s=sessions.find(x=>x.id===id);$('#conversationTitle').textContent=s?.visitor_name||`Visitante ${id.slice(0,8)}`;$('#conversationMeta').textContent=`${s?.status||''} · início ${fmt(s?.started_at)}${s?.triage_submissions?.reference_code?' · '+s.triage_submissions.reference_code:''}`;await loadConversation();subscribeSession();}
  async function loadConversation(){const {data}=await db.from('chat_messages').select('*').eq('session_id',currentSessionId).order('created_at');renderMessages(data||[]);}
  function renderMessages(msgs){const box=$('#conversationMessages');box.innerHTML=msgs.map(m=>`<div class="msg ${m.sender_type}"><div class="bubble">${escapeHtml(m.content)}<small>${m.sender_type==='human'?'Atendente':m.sender_type==='bot'?'IA':m.sender_type==='visitor'?'Visitante':'Sistema'} · ${fmt(m.created_at)}</small></div></div>`).join('');box.scrollTop=box.scrollHeight;}
  function subscribeSession(){if(sessionChannel)db.removeChannel(sessionChannel);sessionChannel=db.channel(`admin-session-${currentSessionId}`).on('postgres_changes',{event:'*',schema:'public',table:'chat_messages',filter:`session_id=eq.${currentSessionId}`},loadConversation).on('postgres_changes',{event:'UPDATE',schema:'public',table:'chat_sessions',filter:`id=eq.${currentSessionId}`},loadSessions).subscribe();}
  function subscribeLive(){liveChannel=db.channel('admin-live').on('postgres_changes',{event:'*',schema:'public',table:'chat_sessions'},loadSessions).subscribe();}
  $('#assumeBtn').addEventListener('click',async()=>{if(!currentSessionId)return;await db.from('chat_sessions').update({status:'human',assigned_admin:user.id,human_requested:false,last_activity:new Date().toISOString()}).eq('id',currentSessionId);await db.from('chat_messages').insert({session_id:currentSessionId,author_id:user.id,role:'system',sender_type:'system',content:'Um atendente da Resumindo Viagens entrou na conversa. A partir de agora, suas mensagens serão respondidas pela equipe.',source:'human-takeover'});loadSessions();});
  $('#releaseBtn').addEventListener('click',async()=>{if(!currentSessionId)return;await db.from('chat_sessions').update({status:'bot',assigned_admin:null,human_requested:false,last_activity:new Date().toISOString()}).eq('id',currentSessionId);await db.from('chat_messages').insert({session_id:currentSessionId,author_id:user.id,role:'system',sender_type:'system',content:'O atendimento automático foi retomado. Você pode continuar fazendo perguntas.',source:'bot-resume'});loadSessions();});
  $('#closeSessionBtn').addEventListener('click',async()=>{if(!currentSessionId||!confirm('Encerrar esta conversa?'))return;await db.from('chat_sessions').update({status:'closed',ended_at:new Date().toISOString(),last_activity:new Date().toISOString()}).eq('id',currentSessionId);loadSessions();});
  $('#humanForm').addEventListener('submit',async e=>{e.preventDefault();const content=$('#humanInput').value.trim();if(!content||!currentSessionId)return;await db.from('chat_sessions').update({status:'human',assigned_admin:user.id,last_activity:new Date().toISOString()}).eq('id',currentSessionId);const {error}=await db.from('chat_messages').insert({session_id:currentSessionId,author_id:user.id,role:'assistant',sender_type:'human',content,source:'human-live'});if(!error)$('#humanInput').value='';});
  $('#createKnowledgeFromChat').addEventListener('click',async()=>{if(!currentSessionId)return;const {data}=await db.from('chat_messages').select('*').eq('session_id',currentSessionId).in('sender_type',['visitor','human']).order('created_at',{ascending:false}).limit(10);const answer=(data||[]).find(m=>m.sender_type==='human');const question=(data||[]).find(m=>m.sender_type==='visitor'&&(!answer||new Date(m.created_at)<=new Date(answer.created_at)));if(!question||!answer)return alert('É necessário haver uma pergunta do visitante e uma resposta humana.');await db.from('review_queue').insert({session_id:currentSessionId,question_message_id:question.id,answer_message_id:answer.id,proposed_question:question.content,proposed_answer:answer.content,created_by:user.id});await loadReviews();showTab('review');});

  async function loadKnowledge(){const {data}=await db.from('knowledge_items').select('*').order('priority',{ascending:false}).order('updated_at',{ascending:false});knowledge=data||[];renderKnowledge();}
  function renderKnowledge(){const term=($('#knowledgeSearch').value||'').toLowerCase();$('#knowledgeList').innerHTML=knowledge.filter(k=>`${k.category} ${k.question} ${k.answer}`.toLowerCase().includes(term)).map(k=>`<div class="item" data-kb="${k.id}"><strong>${escapeHtml(k.question)}</strong><small>${escapeHtml(k.category)} · ${k.active?'publicada':'desativada'} · prioridade ${k.priority}</small></div>`).join('');$$('[data-kb]').forEach(el=>el.addEventListener('click',()=>editKnowledge(el.dataset.kb)));}
  $('#knowledgeSearch').addEventListener('input',renderKnowledge);$('#newKnowledgeBtn').addEventListener('click',()=>editKnowledge());$('#cancelKnowledge').addEventListener('click',()=>$('#knowledgeForm').classList.add('hidden'));
  function editKnowledge(id){activeReviewId=null;const k=knowledge.find(x=>x.id===id)||{};$('#knowledgeForm').classList.remove('hidden');$('#knowledgeId').value=k.id||'';$('#knowledgeFormTitle').textContent=k.id?'Editar resposta':'Nova resposta';$('#knowledgeCategory').value=k.category||'Geral';$('#knowledgeQuestion').value=k.question||'';$('#knowledgeVariations').value=(k.variations||[]).join('\n');$('#knowledgeKeywords').value=(k.keywords||[]).join('\n');$('#knowledgeAnswer').value=k.answer||'';$('#knowledgeMode').value=k.response_mode||'direct';$('#knowledgePriority').value=k.priority??50;$('#knowledgeActive').checked=k.active??true;$('#knowledgeWhatsapp').checked=k.whatsapp_on??false;$('#knowledgeReview').checked=k.requires_review??false;$('#knowledgeValidUntil').value=k.valid_until||'';$('#deleteKnowledge').classList.toggle('hidden',!k.id);}
  $('#knowledgeForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#knowledgeId').value;const payload={category:$('#knowledgeCategory').value.trim(),question:$('#knowledgeQuestion').value.trim(),variations:$('#knowledgeVariations').value.split('\n').map(x=>x.trim()).filter(Boolean),keywords:$('#knowledgeKeywords').value.split('\n').map(x=>x.trim()).filter(Boolean),answer:$('#knowledgeAnswer').value.trim(),response_mode:$('#knowledgeMode').value,priority:Number($('#knowledgePriority').value||50),active:$('#knowledgeActive').checked,whatsapp_on:$('#knowledgeWhatsapp').checked,requires_review:$('#knowledgeReview').checked,valid_until:$('#knowledgeValidUntil').value||null,updated_by:user.id};const query=id?db.from('knowledge_items').update(payload).eq('id',id):db.from('knowledge_items').insert({...payload,created_by:user.id});const {error}=await query;setStatus($('#knowledgeStatus'),error?error.message:'Resposta salva.',error?'error':'success');if(!error){if(activeReviewId){await db.from('review_queue').update({status:'approved',reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq('id',activeReviewId);activeReviewId=null;await loadReviews();}await loadKnowledge();setTimeout(()=>$('#knowledgeForm').classList.add('hidden'),500)}});
  $('#deleteKnowledge').addEventListener('click',async()=>{const id=$('#knowledgeId').value;if(id&&confirm('Excluir esta resposta?')){await db.from('knowledge_items').delete().eq('id',id);$('#knowledgeForm').classList.add('hidden');loadKnowledge();}});

  async function loadTriage(){const {data}=await db.from('triage_questions').select('*').order('sort_order');triage=data||[];renderTriage();}
  function renderTriage(){$('#triageList').innerHTML=triage.map(q=>`<div class="item" data-tq="${q.id}"><strong>${q.sort_order}. ${escapeHtml(q.prompt)}</strong><small>${q.question_key} · ${q.active?'ativa':'desativada'}</small></div>`).join('');$$('[data-tq]').forEach(el=>el.addEventListener('click',()=>editTriage(el.dataset.tq)));}
  $('#newTriageBtn').addEventListener('click',()=>editTriage());$('#cancelTriage').addEventListener('click',()=>$('#triageForm').classList.add('hidden'));
  function editTriage(id){const q=triage.find(x=>x.id===id)||{};$('#triageForm').classList.remove('hidden');$('#triageId').value=q.id||'';$('#triageKey').value=q.question_key||'';$('#triagePrompt').value=q.prompt||'';$('#triageHelp').value=q.help_text||'';$('#triageType').value=q.input_type||'choice';$('#triageOrder').value=q.sort_order??10;$('#triageOptions').value=(q.options||[]).map(o=>`${o.value} | ${o.label}`).join('\n');$('#triageConditionKey').value=q.condition_question_key||'';$('#triageConditionValues').value=(q.condition_values||[]).join('\n');$('#triageWhatsappLabel').value=q.whatsapp_label||'';$('#triageRequired').checked=q.required??true;$('#triageActive').checked=q.active??true;$('#triageInclude').checked=q.include_in_whatsapp??true;}
  $('#triageForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#triageId').value;const options=$('#triageOptions').value.split('\n').map(line=>{const [value,...label]=line.split('|');return value?.trim()&&label.join('|').trim()?{value:value.trim(),label:label.join('|').trim()}:null}).filter(Boolean);const payload={question_key:$('#triageKey').value.trim(),prompt:$('#triagePrompt').value.trim(),help_text:$('#triageHelp').value.trim()||null,input_type:$('#triageType').value,sort_order:Number($('#triageOrder').value||10),options,condition_question_key:$('#triageConditionKey').value.trim()||null,condition_values:$('#triageConditionValues').value.split('\n').map(x=>x.trim()).filter(Boolean),whatsapp_label:$('#triageWhatsappLabel').value.trim(),required:$('#triageRequired').checked,active:$('#triageActive').checked,include_in_whatsapp:$('#triageInclude').checked,updated_by:user.id,updated_at:new Date().toISOString()};const q=id?db.from('triage_questions').update(payload).eq('id',id):db.from('triage_questions').insert(payload);const {error}=await q;setStatus($('#triageStatus'),error?error.message:'Pergunta salva.',error?'error':'success');if(!error){loadTriage();setTimeout(()=>$('#triageForm').classList.add('hidden'),500)}});

  async function loadReviews(){const {data}=await db.from('review_queue').select('*').order('created_at',{ascending:false});reviews=data||[];renderReviews();}
  function renderReviews(){$('#reviewList').innerHTML=reviews.map(r=>`<div class="review-card"><strong>${escapeHtml(r.proposed_question)}</strong><blockquote>${escapeHtml(r.proposed_answer)}</blockquote><small>${r.status} · ${fmt(r.created_at)}</small>${r.status==='pending'?`<div class="form-actions"><button data-review-approve="${r.id}">Revisar e publicar</button><button class="danger" data-review-reject="${r.id}">Descartar</button></div>`:''}</div>`).join('')||'<div class="empty">Nenhuma sugestão pendente.</div>';$$('[data-review-approve]').forEach(b=>b.addEventListener('click',()=>approveReview(b.dataset.reviewApprove)));$$('[data-review-reject]').forEach(b=>b.addEventListener('click',async()=>{await db.from('review_queue').update({status:'rejected',reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq('id',b.dataset.reviewReject);loadReviews()}));}
  function approveReview(id){const r=reviews.find(x=>x.id===id);if(!r)return;showTab('knowledge');editKnowledge();activeReviewId=id;$('#knowledgeQuestion').value=r.proposed_question;$('#knowledgeAnswer').value=r.proposed_answer;$('#knowledgeCategory').value=r.category||'Geral';}

  init().catch(err=>setStatus($('#loginStatus'),err.message,'error'));
})();